name: Deploy
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'
      commitId:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'

  push:
    branches:
      - master
jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin


